### ISSUE TITLE
Error if i scan qr code !

### ISSUE THREAD

**Issue by Clou1dx** [DismissedGuy/Discord-QR-Auth-Client#24] opened 2023-07-29 22:05 UTC
Attempting server handshake...
Please scan the QR code to continue.
Exch ticket: CENSORED 
argument should be a bytes-like object or ASCII string, not 'NoneType'
----------------------
Connection closed: Handshake Error
Save to info.txt? [Y/n] >

**Comment by malmeloo** [comment] 2023-07-30 21:00
Closing as duplicate of #22

**Closed as completed** 2023-07-30 21:01 UTC
Labels: duplicate
